Edit the README.md file
GSG-FC03/Book-App pull request #14
Opened 2021-08-06 07:12 UTC by Aya74

Edit the README.md file by adding this content to it:
-  The name of the project which is Book App.
-  The link of the figma (design created to the app).
- The problem that lead us to create the app and the solution of it.
-  The initial design or sketch to the app (wireframe).
-  User journey.
- User stories.
- The way to installation the project to run it locally.
- Tech stack that we used in our project and the main purpose of it.
- Team members.

relates #3

2021-08-06 08:08 UTC, sara219 requested changes

2021-08-06 08:08 UTC, sara219 commented on README.md
> +# The name of project
you don't have to write 'the name of the project' , just go with the name straightly

# Book App

2021-08-06 08:08 UTC, sara219 commented on README.md
> +[Figma link](https://www.figma.com/file/X183PfgsEmdP7wW3f2HMxF/Untitled?node-id=0%3A1) .
add the APIs documentation link

2021-08-07 14:43 UTC, sara219 approved these changes

2021-08-07 15:08 UTC, adnan-afana approved these changes

2021-08-07 16:28 UTC, suhail-radwan approved these changes

2021-08-07 17:25 UTC, merged