Display Book I want to search in Book Result
GSG-FC03/Book-App pull request #36
Opened 2021-08-10 09:31 UTC by WessalJawad95

- [ ]  using for loop to appear 10 Books of search result

- [ ] create Element :

- create Element (img) to appear the image of book
- create Element (div) to appear card content
- create Element (h4) to appear card-content-title
- create Element (p) to appear card-content-description

2021-08-11 19:05 UTC, Aya74 submitted a review, later dismissed

2021-08-11 20:49 UTC, adnan-afana approved these changes, later dismissed

2021-08-12 06:10 UTC, HalaSalim77 approved these changes, later dismissed

2021-08-12 06:28 UTC, sara219 approved these changes

2021-08-12 08:07 UTC, sara219 requested changes
resolve the conflict

2021-08-12 11:30 UTC, sara219 approved these changes

2021-08-12 11:37 UTC, suhail-radwan approved these changes

2021-08-12 12:11 UTC, adnan-afana approved these changes

2021-08-12 12:11 UTC, merged